alias: Load Shedding (Stage)
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.load_shedding_stage_eskom
    attribute: stage
condition: []
action:
  - service: notify.mobile_app_nokia_8_sirocco
    data:
      title: Load Shedding
      message: |-
        {% if is_state_attr(trigger.entity_id, "stage", 0) %}
          Suspended
        {% else %}
          {{ states(trigger.entity_id) }}
        {% endif %}
    enabled: "true"
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: time
                after: input_datetime.sleep
                weekday:
                  - mon
                  - tue
                  - wed
                  - thu
                  - fri
                  - sat
                  - sun
              - condition: time
                before: input_datetime.wake
                weekday:
                  - sun
                  - sat
                  - fri
                  - thu
                  - wed
                  - tue
                  - mon
        sequence:
          - wait_for_trigger:
              - platform: time
                at: input_datetime.wake
            continue_on_timeout: "false"
    default: []
  - service: tts.home_assistant_say
    data:
      entity_id: media_player.assistant_speakers
      cache: "true"
      message: |-
        Load Shedding {% if is_state_attr(trigger.entity_id, "stage", 0) %}
          Suspended
        {% else %}
          {{ states(trigger.entity_id) }}
        {% endif %}
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - if:
      - condition: state
        entity_id: sensor.load_shedding_area_eskde_14_milnertoncityofcapetownwesterncape
        state: "on"
    then:
      - service: tts.home_assistant_say
        data:
          message: Load shedding imminent!
          entity_id: media_player.assistant_speakers
          cache: "true"
mode: single
